// Decoding, against bytes the server actually sent.
//
// These fixtures are bytes the server sent, captured by
// `scripts/capture-companion-fixtures.mjs` against a harness started on a
// temporary HOME. That matters more than it sounds: hand-written test JSON
// tests our idea of the API, and the whole risk in a two-language client is
// that our idea drifts from the API without anything failing. When a server
// payload changes, re-capturing makes these fail, which is the alarm.
//
// One exception, and it is marked in the script: options-card.json needs a
// bot to actually ask for approval, which needs a real provider and a real
// turn, so it is not regenerated by a run.
import XCTest
@testable import CompanionCore

final class DecodingTests: XCTestCase {
    // MARK: - Fixtures

    func fixture(_ name: String) throws -> Data {
        guard let url = Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures")
            ?? Bundle.module.url(forResource: name, withExtension: "json")
        else {
            XCTFail("missing fixture \(name).json — run scripts/capture-companion-fixtures.mjs")
            throw CocoaError(.fileNoSuchFile)
        }
        return try Data(contentsOf: url)
    }

    func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        try JSONDecoder().decode(type, from: try fixture(name))
    }

    // MARK: - Hydration

    func testDecodesThePagedFleet() throws {
        let fleet = try decode(Fleet.self, "bots-paged")
        XCTAssertFalse(fleet.bots.isEmpty)

        let bot = try XCTUnwrap(fleet.bots.first)
        XCTAssertFalse(bot.id.isEmpty)
        XCTAssertFalse(bot.threadId.isEmpty)
        XCTAssertFalse(bot.name.isEmpty)
        XCTAssertNotNil(bot.messages)

        // the paged shape caps each thread and says whether there is more
        let room = try XCTUnwrap(fleet.groups.first)
        XCTAssertEqual(room.messages?.count, 3)
        XCTAssertEqual(room.hasMore, true)
    }

    func testDecodesTheFullFleetToo() throws {
        // omitting ?messages must stay decodable by the same types — it is
        // what the desktop gets, and what a phone falls back to
        let fleet = try decode(Fleet.self, "bots-full")
        XCTAssertFalse(fleet.bots.isEmpty)
        XCTAssertNil(fleet.bots.first?.hasMore)
    }

    func testOldAndNewAvatarProfilesDecodeTogether() throws {
        let oldBot = try XCTUnwrap(decode(Fleet.self, "bots-full").bots.first)
        XCTAssertNil(oldBot.avatarUrl)
        XCTAssertNil(oldBot.avatarCrop)

        let newBot = try XCTUnwrap(decode(Fleet.self, "bot-avatar-profile").bots.first)
        XCTAssertEqual(newBot.avatarUrl, "/api/attachments/123e4567-e89b-12d3-a456-426614174000.webp")
        XCTAssertEqual(newBot.avatarCrop, .rounded)
        XCTAssertEqual(newBot.voice, "voice-1")
        XCTAssertEqual(newBot.speakReplies, true)
    }

    func testFutureAvatarCropFallsBackWithoutDroppingTheBot() throws {
        let fixture = String(decoding: try fixture("bot-avatar-profile"), as: UTF8.self)
            .replacingOccurrences(of: #""avatarCrop":"rounded""#, with: #""avatarCrop":"hexagon""#)
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(fixture.utf8))

        XCTAssertEqual(fleet.bots.count, 1)
        XCTAssertEqual(fleet.bots.first?.avatarCrop, .mascot)
    }

    func testFutureRoutineScheduleKindRemainsVisibleAsUnknown() throws {
        let schedule = try JSONDecoder().decode(
            RoutineSchedule.self,
            from: Data(#"{"type":"weekly","time":"09:00","weekdays":[1]}"#.utf8)
        )

        XCTAssertEqual(schedule.type, .unknown)
        XCTAssertEqual(schedule.time, "09:00")
        XCTAssertEqual(schedule.weekdays, [1])
    }

    func testNotificationTargetRequiresBothExactIds() {
        XCTAssertEqual(
            NotificationTarget(payload: ["botId": "bot-1", "threadId": "detached-task-2"]),
            NotificationTarget(botId: "bot-1", threadId: "detached-task-2")
        )
        XCTAssertNil(NotificationTarget(payload: ["botId": "bot-1"]))
        XCTAssertNil(NotificationTarget(payload: ["threadId": "task-1"]))
        XCTAssertNil(NotificationTarget(botId: " ", threadId: "task-1"))
        guard let detached = NotificationTarget(botId: "bot-1", threadId: "task-2") else {
            return XCTFail("valid notification target")
        }
        XCTAssertTrue(detached.requiresTaskSwitch(activeThreadId: "task-1"))
        XCTAssertFalse(detached.requiresTaskSwitch(activeThreadId: "task-2"))
    }

    func testDecodesMultipleConnectedAccountsAndNoAuthToolkit() throws {
        let payload = #"""
        {
          "configured": true,
          "services": {
            "gmail": {
              "connected": true,
              "pending": false,
              "status": "ACTIVE",
              "accounts": [
                {"id": "ca_work", "alias": "Work", "status": "ACTIVE"},
                {"id": "ca_personal", "status": "ACTIVE"}
              ]
            },
            "weather": {
              "connected": true,
              "pending": false,
              "status": "ACTIVE",
              "accounts": []
            }
          }
        }
        """#
        let statuses = try JSONDecoder().decode(ConnectorStatuses.self, from: Data(payload.utf8))
        let gmail = try XCTUnwrap(statuses.services["gmail"])
        XCTAssertEqual(gmail.accounts?.map(\.id), ["ca_work", "ca_personal"])
        XCTAssertEqual(gmail.accounts?.first?.alias, "Work")
        XCTAssertNil(gmail.accounts?.last?.alias)

        let noAuth = try XCTUnwrap(statuses.services["weather"])
        XCTAssertTrue(noAuth.connected)
        XCTAssertEqual(noAuth.accounts?.isEmpty, true)

        let disabled = try JSONDecoder().decode(
            ConnectorStatuses.self,
            from: Data(#"{"configured":false,"services":{}}"#.utf8)
        )
        XCTAssertFalse(disabled.configured)
        XCTAssertTrue(disabled.services.isEmpty)
    }

    func testDecodesTheCloudBackendAndItsAbsence() throws {
        // The cloud-desktop button hides on cloudBackend == "vps", so both
        // sides of that gate must decode: a harness that sends the field, and
        // an older one that has never heard of it (nil keeps the button).
        let json = """
        {
          "bots": [
            {
              "id":"b1","threadId":"t1","name":"Scout","title":"","description":"",
              "notifications":true,"color":"green","unread":false,
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":1,
              "computer":"cloud","cloudBackend":"vps"
            },
            {
              "id":"b2","threadId":"t2","name":"Rio","title":"","description":"",
              "notifications":true,"color":"blue","unread":false,
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":2,
              "computer":"cloud"
            }
          ],
          "groups": []
        }
        """
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(json.utf8))
        XCTAssertEqual(fleet.bots.first?.cloudBackend, "vps")
        XCTAssertNil(fleet.bots.last?.cloudBackend)
    }

    func testOneMalformedBotDoesNotHideTheRestOfTheFleet() throws {
        let json = """
        {
          "bots": [
            {"id":"broken","threadId":42},
            {
              "id":"good","threadId":"t1","name":"Scout","title":"","description":"",
              "notifications":true,"color":"green","unread":false,
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":1
            }
          ],
          "groups": []
        }
        """
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(json.utf8))
        XCTAssertEqual(fleet.bots.map(\.id), ["good"])
    }

    func testNeverDecodesProviderSessionCursors() throws {
        // resumeCursors is harness bookkeeping and must not be on the wire.
        // Asserted against the raw bytes, because a Swift type that simply
        // lacks the field would hide it.
        for name in ["bots-full", "bots-paged", "sse-frames"] {
            let raw = String(decoding: try fixture(name), as: UTF8.self)
            XCTAssertFalse(raw.contains("resumeCursors"), "\(name) carries provider session cursors")
        }
    }

    func testDecodesAThreadPage() throws {
        let page = try decode(ThreadPage.self, "thread-page")
        XCTAssertEqual(page.messages.count, 2)
        XCTAssertEqual(page.hasMore, true)
        // pages arrive oldest-first, which is what makes prepending correct
        let times = page.messages.map(\.at)
        XCTAssertEqual(times, times.sorted())
    }

    // MARK: - Messages and cards

    func testDecodesAnOptionsCard() throws {
        let message = try decode(Message.self, "options-card")
        XCTAssertEqual(message.kind, .options)
        XCTAssertEqual(message.role, .bot)
        let card = try XCTUnwrap(message.card)
        XCTAssertFalse(card.options.isEmpty)
        // the onboarding card has no request behind it, so it is history
        XCTAssertFalse(card.isPending)
        XCTAssertFalse(card.isPermission)
    }

    func testAPendingApprovalIsActionableAndAnAnsweredOneIsNot() throws {
        // The shape a live permission request takes, which the fixture rig
        // cannot produce without a real provider attached.
        let json = """
        {
          "id": "m1", "role": "bot", "kind": "options", "at": 1786742413762,
          "card": {
            "title": "Approval needed", "subtitle": "rm -rf ./build",
            "options": ["Allow", "Deny"], "requestId": "req-1",
            "tool": "Bash", "allowKey": "Bash:rm"
          }
        }
        """
        let card = try XCTUnwrap(try JSONDecoder().decode(Message.self, from: Data(json.utf8)).card)
        XCTAssertTrue(card.isPending)
        XCTAssertTrue(card.isPermission)
        XCTAssertEqual(card.allowKey, "Bash:rm")

        var answered = card
        answered.answered = "Allow"
        XCTAssertFalse(answered.isPending, "an answered card must stop offering buttons")

        var dismissed = card
        dismissed.dismissed = true
        XCTAssertFalse(dismissed.isPending)
    }

    func testDecodesAMessageThatGainedAFieldWeDoNotKnow() throws {
        // The harness ships ahead of the app. An unknown key must not cost
        // the user their conversation.
        let json = """
        {"id":"m2","role":"user","kind":"text","at":1,"text":"hi","somethingNew":{"a":1}}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.text, "hi")
    }

    // MARK: - Pairing and errors

    func testDecodesThePairResponse() throws {
        let paired = try decode(PairResponse.self, "pair-response")
        XCTAssertTrue(paired.token.hasPrefix("omb_"))
        XCTAssertEqual(paired.device.name, "Ada's iPhone")
        XCTAssertFalse(paired.serverName.isEmpty)
    }

    func testDecodesTheHarnessErrorBodies() throws {
        // these strings are written for people, and the client shows them
        // rather than inventing its own
        XCTAssertTrue(try decode(APIErrorBody.self, "unauthorized").error.contains("pair"))
        XCTAssertFalse(try decode(APIErrorBody.self, "forbidden").error.isEmpty)
        XCTAssertFalse(try decode(APIErrorBody.self, "pair-rejected").error.isEmpty)
    }

    func testDecodesInstancesAndConfig() throws {
        let instances = try decode(InstanceList.self, "instances").instances
        // Availability is a property of the machine that captured the
        // fixture, not of the wire contract. Pin the required identity and
        // catalog shape without making a developer's installed CLIs decide
        // whether this test passes.
        let instance = try XCTUnwrap(instances.first)
        XCTAssertFalse(instance.instanceId.isEmpty)
        XCTAssertFalse(instance.driverKind.isEmpty)

        let config = try decode(ConfigStatus.self, "config")
        XCTAssertEqual(config.profile?.name, "Ada Lovelace")
        XCTAssertEqual(config.box?.configured, false)
    }

    // MARK: - Frames

    func testDecodesEveryCapturedFrame() throws {
        let frames = try decode([StreamFrame].self, "sse-frames")
        XCTAssertFalse(frames.isEmpty)

        var kinds: [String] = []
        for streamFrame in frames {
            switch streamFrame.frame {
            case let .hello(cursor, resumed):
                kinds.append("hello")
                XCTAssertTrue(cursor.contains(":"))
                XCTAssertFalse(resumed, "a cold connection has nothing to resume")
                XCTAssertNil(streamFrame.seq, "hello is not a replayable frame")
            case let .message(threadId, message):
                kinds.append("message")
                XCTAssertFalse(threadId.isEmpty)
                XCTAssertFalse(message.id.isEmpty)
                XCTAssertNotNil(streamFrame.seq)
            case let .bot(bot):
                kinds.append("bot")
                XCTAssertFalse(bot.id.isEmpty)
                XCTAssertNil(bot.messages, "bot frames carry no transcript")
            case let .unknown(kind):
                XCTFail("unhandled frame kind in fixtures: \(kind)")
            default:
                kinds.append("other")
            }
        }
        XCTAssertTrue(kinds.contains("hello"))
        XCTAssertTrue(kinds.contains("message"))
        XCTAssertTrue(kinds.contains("bot"))
    }

    func testAnUnknownFrameKindIsAbsorbedRatherThanThrown() throws {
        // the harness will add frame kinds; an old app must keep folding the
        // ones it knows instead of tearing down its stream
        let frame = try JSONDecoder().decode(
            StreamFrame.self,
            from: Data(#"{"kind":"routine.run","run":{"id":"r1"},"seq":9}"#.utf8)
        )
        XCTAssertEqual(frame.seq, 9)
        guard case let .unknown(kind) = frame.frame else {
            return XCTFail("expected .unknown, got \(frame.frame)")
        }
        XCTAssertEqual(kind, "routine.run")
    }

    func testDecodesANotifyFrame() throws {
        let json = """
        {"kind":"notify","seq":12,"notification":{
          "kind":"approval","botId":"b1","botName":"Scout","threadId":"t1",
          "title":"Scout needs approval","body":"rm -rf ./build"}}
        """
        let frame = try JSONDecoder().decode(StreamFrame.self, from: Data(json.utf8))
        guard case let .notify(notification) = frame.frame else {
            return XCTFail("expected .notify")
        }
        XCTAssertTrue(notification.isBlocking)
        XCTAssertEqual(notification.threadId, "t1")
        XCTAssertEqual(frame.frame.threadId, "t1")
    }

    // MARK: - A newer computer than the phone

    // The harness gains message kinds when it ships; the phone gains them
    // when the App Store gets round to it. So the phone talking to a newer
    // computer is the ordinary case, and it must survive one.

    func testAnUnknownMessageKindDecodes() throws {
        let json = """
        {"id":"m1","role":"bot","kind":"webhook","at":1,"text":"Stripe fired"}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.kind, .unknown)
        // and keeps what it can show
        XCTAssertEqual(message.text, "Stripe fired")
    }

    func testAnUnknownRoleIsNotAttributedToYou() throws {
        let json = """
        {"id":"m1","role":"system","kind":"text","at":1,"text":"hello"}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.role, .bot)
    }

    /// The one that matters. `kind` is not optional, so before this a single
    /// unrecognised message failed the decode of the entire response — the
    /// thread did not render one message oddly, it did not render.
    func testOneUnknownMessageDoesNotSinkThePage() throws {
        let json = """
        {"messages":[
          {"id":"m1","role":"user","kind":"text","at":1,"text":"go"},
          {"id":"m2","role":"bot","kind":"something-new","at":2,"text":"working"},
          {"id":"m3","role":"bot","kind":"text","at":3,"text":"done"}
        ],"hasMore":false}
        """
        let page = try JSONDecoder().decode(ThreadPage.self, from: Data(json.utf8))
        XCTAssertEqual(page.messages.count, 3)
        XCTAssertEqual(page.messages.map(\.kind), [.text, .unknown, .text])
        XCTAssertEqual(page.messages.map(\.id), ["m1", "m2", "m3"])
    }

    /// Same page, arriving one message at a time down the stream.
    func testAnUnknownMessageArrivesOverTheStream() throws {
        let json = """
        {"kind":"message","seq":3,"threadId":"t1",
         "message":{"id":"m9","role":"bot","kind":"routine.run","at":9,"text":"ran"}}
        """
        let frame = try JSONDecoder().decode(StreamFrame.self, from: Data(json.utf8))
        guard case let .message(threadId, message) = frame.frame else {
            return XCTFail("expected .message, got \(frame.frame)")
        }
        XCTAssertEqual(threadId, "t1")
        XCTAssertEqual(message.kind, .unknown)
        XCTAssertEqual(message.text, "ran")
    }
}
